/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Services.BeneficiarioImpl;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FrmResoluciones extends javax.swing.JInternalFrame {

    /**
     * Este es el constructor del Form Resoluciones
     */
    public FrmResoluciones() {
        initComponents();
        iniciotabla();
        iniciotablab();

    }

    /**
     *
     * Procedimiento para inicializar valores de tabla que se muestran en
     * formulario Se cargan los Primeros 10 campos en el modelo y se cargan en
     * la tabla
     */
    private void iniciotabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Num_Resolucion");
        modelo.addColumn("Cedula_Principal");
        modelo.addColumn("Nombre_Principal");
        modelo.addColumn("Apellido_Principal");
        modelo.addColumn("Fecha Resolucion");
        modelo.addColumn("Fam. Beneficiarias");
        modelo.addColumn("Monto");
        modelo.addColumn("Emitida por");
        modelo.addColumn("Fecha Registro");
        modelo.addColumn("Depto Origen");
        modelo.addColumn("Municipio Origen");
        tabla.setModel(modelo);
    }

    /**
     * Función que convierte Fecha acadena de Caracteres
     *
     * @param dateParameter El parámetro contiene la fecha en formato Date a
     * Convertir en Cadena String
     * @return El valor que devuelve - Fecha en Formato Cadena -yyyy-MM-dd
     */
    public String fechaAString(Date dateParameter) {

        String unafecha = null;
        Date fecha = dateParameter;
        long d = fecha.getTime();
        java.sql.Date dateFinal = new java.sql.Date(d);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            unafecha = sdf.format(dateFinal);
        } catch (Exception e) {
            System.out.println("e = " + e.getMessage());
        }
        return unafecha;
    }

    /*
    Configuración de la Tabla de Beneficiarios
    Inicialmnente sólo contiene Cuatro campos
    1-Resolución
    2- C.C. Beneficiario
    3- Nombre Beneficiario
    4- Apellido Beneficiario
     */
    private void iniciotablab() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Resolucion");
        modelo.addColumn("Tipo Documento");
        modelo.addColumn("Numero Documento");
        modelo.addColumn("Nombre Beneficiario");
        modelo.addColumn("Apellido Beneficiario");
        tablab.setModel(modelo);
    }

    /**
     * Función que convierte Cadena de Caracteres a Fecha SQL - Base de datos
     *
     * @param cadena La cadena que contine la fecha en formato Date a Convertir
     * a Date en SQL
     * @return El valor que devuelve - Date en SQL EN el Formato Indicado
     * -yyyy-MM-dd
     */
    public java.sql.Date cadenaAfecha(String cadena) {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate ff = LocalDate.parse(cadena, dtf);
        java.sql.Date res = java.sql.Date.valueOf(ff);
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestResoluciones = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtidresolucion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtbeneficiarias = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtmonto = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtemitidapor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnumresolucion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtcedulaprincipal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnimprimir = new javax.swing.JButton();
        btnbeneficiarios = new javax.swing.JButton();
        lblcantbeneficiarios = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnomprincipal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtapeprincipal = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cbodepto = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cbomunicipio = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        optdocumento = new javax.swing.JRadioButton();
        optresolucion = new javax.swing.JRadioButton();
        txtbuscar = new javax.swing.JTextField();
        jdcfresol = new com.toedter.calendar.JDateChooser();
        jdcfregistro = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtnombrebeneficiario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtapellidobeneficiario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnLimpiarb = new javax.swing.JButton();
        btnAgregarb = new javax.swing.JButton();
        btneliminarb = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnActualizarb = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtnumresolucionb = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtbuscarb = new javax.swing.JTextField();
        btnbuscarb = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablab = new javax.swing.JTable();
        btnimprimir1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cbotipodocumento = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtidbeneficiario = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pestResoluciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Id_Resolucion");

        jLabel2.setText("Fecha Resolución");

        jLabel3.setText("Beneficiarias");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Formulario de Resoluciones");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");

        btneliminar.setText("Eliminar");

        jLabel5.setText("Monto");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel6.setText("Emitida por");

        jLabel7.setText("Fecha Registro");

        jLabel8.setText("#  Resolucion");

        jLabel10.setText("Cedula Principal");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnimprimir.setText("Imprimir");

        btnbeneficiarios.setText("Beneficiarios");

        lblcantbeneficiarios.setText("Beneficiarios en Resolucion :");

        jLabel11.setText("Nombres Ppal");

        jLabel12.setText("Apellidos Ppal");

        btnbuscar.setText("Buscar");

        jLabel17.setText("Depto origen");

        cbodepto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antioquia", "Atlántico", "Bogotá", "Bolívar", "Boyacá", "Caldas", "Caquetá", "Cauca", "Chocó", "Huila", "Meta", "Nariño", "Norte de Santander", "Putumayo", "Risaralda", "Santander", "Tolima", "Valle", "Vichada", " " }));
        cbodepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbodeptoActionPerformed(evt);
            }
        });

        jLabel21.setText("Ciudad Origen");

        jLabel9.setText("Buscar ");

        optdocumento.setText("Por Documento");
        optdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optdocumentoActionPerformed(evt);
            }
        });

        optresolucion.setText("Por  Resolucion");
        optresolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optresolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel21)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtidresolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcedulaprincipal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtnumresolucion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtnomprincipal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtapeprincipal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtbeneficiarias, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtmonto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtemitidapor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbodepto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbomunicipio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdcfresol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdcfregistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(optdocumento)
                                .addGap(59, 59, 59)
                                .addComponent(optresolucion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtbuscar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar)
                        .addGap(35, 35, 35)
                        .addComponent(btneliminar)
                        .addGap(49, 49, 49)
                        .addComponent(btnimprimir)
                        .addGap(48, 48, 48)
                        .addComponent(btnbeneficiarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblcantbeneficiarios, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(159, 159, 159)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAgregar, btnLimpiar, btneliminar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtidresolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(optdocumento)
                            .addComponent(optresolucion)
                            .addComponent(btnbuscar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtnumresolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtcedulaprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtnomprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtapeprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jdcfresol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtbeneficiarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtemitidapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jdcfregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cbodepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(cbomunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblcantbeneficiarios))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btnActualizar)
                            .addComponent(btnAgregar)
                            .addComponent(btneliminar)
                            .addComponent(btnimprimir)
                            .addComponent(btnbeneficiarios))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAgregar, btnLimpiar, btneliminar});

        pestResoluciones.addTab("Resoluciones", jPanel1);

        jLabel13.setText("Nombres");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Formulario de Beneficiarios");

        btnLimpiarb.setText("Limpiar");
        btnLimpiarb.setActionCommand("Limpiar_Bene");

        btnAgregarb.setText("Agregar");
        btnAgregarb.setActionCommand("Agregar_Bene");

        btneliminarb.setText("Eliminar");
        btneliminarb.setActionCommand("Eliminar_Bene");

        jLabel15.setText("Apellidos");

        btnActualizarb.setText("Actualizar");
        btnActualizarb.setActionCommand("Act_Bene");

        jLabel18.setText("#  Resolucion");

        jLabel19.setText("Cedula Beneficiario");

        btnbuscarb.setText("Buscar");

        tablab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablabMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablab);

        btnimprimir1.setText("Imprimir");
        btnimprimir1.setActionCommand("Imprimir_Bene");

        jLabel20.setText("Buscar  por Documento");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtbuscarb, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(btnbuscarb, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3))
                        .addGap(111, 111, 111))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnimprimir1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbuscarb)
                    .addComponent(txtbuscarb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnimprimir1))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        cbotipodocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NUIP", "Registro Civil  de Nacimiento", "Cedula de Ciudadania" }));

        jLabel16.setText("Tpo Documento");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnLimpiarb)
                                .addGap(39, 39, 39)
                                .addComponent(btnActualizarb)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(btneliminarb))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnumresolucionb, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(txtnombrebeneficiario, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(txtapellidobeneficiario, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(cbotipodocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtidbeneficiario))))))
                .addGap(53, 53, 53)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jLabel14)
                            .addGap(38, 38, 38)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(txtnumresolucionb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(cbotipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(txtidbeneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(txtnombrebeneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(23, 23, 23)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15)
                                .addComponent(txtapellidobeneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(187, 187, 187)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnLimpiarb)
                                .addComponent(btnActualizarb)
                                .addComponent(btnAgregarb)
                                .addComponent(btneliminarb)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1171, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(60, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(86, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pestResoluciones.addTab("Beneficiarios", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pestResoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 1282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestResoluciones, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Al dar click sobre la tabla todos los campos de la respectiva fila se
     * mueven esos valores a los correspondientes campos del formulario para su
     * manipulación
     *
     * @param evt
     */
    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // Esto ocurre cuando doy click en la tabla

        int fila = tabla.getSelectedRow();
        int numres = Integer.parseInt(String.valueOf(this.tabla.getValueAt(fila, 0)));
        int numbenef = 0;
        txtidresolucion.setText(String.valueOf(this.tabla.getValueAt(fila, 0)));
        txtnumresolucion.setText(String.valueOf(this.tabla.getValueAt(fila, 1)));
        txtcedulaprincipal.setText(String.valueOf(this.tabla.getValueAt(fila, 2)));
        txtnomprincipal.setText(String.valueOf(this.tabla.getValueAt(fila, 3)));
        txtapeprincipal.setText(String.valueOf(this.tabla.getValueAt(fila, 4)));
        jdcfresol.setDate(cadenaAfecha(String.valueOf(this.tabla.getValueAt(fila, 5))));
        txtbeneficiarias.setText(String.valueOf(this.tabla.getValueAt(fila, 6)));
        txtmonto.setText(String.valueOf(this.tabla.getValueAt(fila, 7)));
        txtemitidapor.setText(String.valueOf(this.tabla.getValueAt(fila, 8)));
        jdcfregistro.setDate(cadenaAfecha(String.valueOf(this.tabla.getValueAt(fila, 9))));
        //cbodepto.setSelectedItem(String.valueOf(this.tabla.getValueAt(fila, 10)));
        cbodepto.setSelectedItem(tabla.getValueAt(fila, 10));
        cbomunicipio.setSelectedItem(tabla.getValueAt(fila, 11));

        BeneficiarioImpl beneDAO = new BeneficiarioImpl();
        numbenef = beneDAO.selectcantbene(numres);
        this.lblcantbeneficiarios.setText("Beneficiarios en Resolucion :" + String.valueOf(numbenef));
        //JOptionPane.showMessageDialog(null, String.valueOf(numbenef));
    }//GEN-LAST:event_tablaMouseClicked

    private void optdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optdocumentoActionPerformed
        // Si selecciona Resolución que hago? La marco y desmarco la otra
        //Este es el funcionamiento de los radio buttons
        optdocumento.setSelected(true);
        optresolucion.setSelected(false);
    }//GEN-LAST:event_optdocumentoActionPerformed

    private void optresolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optresolucionActionPerformed
        //Si selecciona Emisor que hago? Marco emisor y desmarco por Resolucion
        //Este es el funcionamiento de los radio buttons
        optdocumento.setSelected(false);
        optresolucion.setSelected(true);
    }//GEN-LAST:event_optresolucionActionPerformed

    private void tablabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablabMouseClicked
        // Me ubico en esta fila para seleccionar la fila actual y
        // con base en esto pivotear los datos a los campos del formulario
        int fila = tablab.getSelectedRow();

        txtnumresolucionb.setText(String.valueOf(this.tablab.getValueAt(fila, 0)));
        cbotipodocumento.setSelectedItem(String.valueOf(this.tablab.getValueAt(fila, 1)));
        txtidbeneficiario.setText(String.valueOf(this.tablab.getValueAt(fila, 2)));
        txtnombrebeneficiario.setText(String.valueOf(this.tablab.getValueAt(fila, 3)));
        txtapellidobeneficiario.setText(String.valueOf(this.tablab.getValueAt(fila, 4)));
    }//GEN-LAST:event_tablabMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // Limpiar los campos  de ingreso a este formulario:
        txtidresolucion.setText("");
        txtnumresolucion.setText("");
        txtnumresolucionb.setText("");
        txtcedulaprincipal.setText("");
        txtnomprincipal.setText("");
        txtapeprincipal.setText("");
        jdcfresol.setDate(null);
        txtbeneficiarias.setText("");
        txtmonto.setText("");
        txtemitidapor.setText("");
        jdcfregistro.setDate(null);
        txtbuscar.setText("");
        cbodepto.setSelectedItem("");
        cbomunicipio.setSelectedItem("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void cbodeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbodeptoActionPerformed
        // TODO add your handling code here:
        String deptoSeleccionado = "";
//        MunicipioDAO municipiodao = new MunicipioDAO();
//        ArrayList<String> lista1 = new  ArrayList<>();
        deptoSeleccionado = cbodepto.getSelectedItem().toString();
        switch (deptoSeleccionado) {
            case "Antioquia": //1
                cbomunicipio.removeAllItems();
//                lista1 = municipiodao.selectPorDepto(1);
//                lista.stream().;
//                lista1.stream().forEach(x -> cbomunicipio.addItem(x));
                cbomunicipio.addItem("Amalfi");
                cbomunicipio.addItem("Carepa");
                cbomunicipio.addItem("El Jardín");
                cbomunicipio.addItem("Ituango");
                cbomunicipio.addItem("Medellín");
                cbomunicipio.addItem("Segovia");
                break;
            case "Atlántico"://3
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Barranquilla");
                break;
            case "Bogotá"://8
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Bogotá");
                break;
            case "Bolívar"://18
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Turbaná");
                break;
            case "Boyacá"://19
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Gachantivá");
                break;
            case "Caldas"://11
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Riosucio");
                cbomunicipio.addItem("Supía");
                break;
            case "Caquetá"://4
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Belen de los Andaquíes");
                cbomunicipio.addItem("Florencia");
                cbomunicipio.addItem("San Vicente");
                break;
            case "Cauca"://9
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Argelia");
                cbomunicipio.addItem("Corinto");
                cbomunicipio.addItem("Popayán");
                cbomunicipio.addItem("Silvia");
                cbomunicipio.addItem("Sucre");
                cbomunicipio.addItem("Toribío");
                break;
            case "Chocó"://5
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Bagadó");
                cbomunicipio.addItem("Medio Atrato");
                cbomunicipio.addItem("Novita");
                cbomunicipio.addItem("Quibdo");
                cbomunicipio.addItem("San José de Atrato");
                cbomunicipio.addItem("San José del Palmar");
                break;
            case "Meta"://12
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Acacías");
                cbomunicipio.addItem("Villavicencio");
                break;
            case "Huila"://6
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Neiva");
                cbomunicipio.addItem("Santa María");
                break;
            case "Nariño"://7
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Cumbitara");
                cbomunicipio.addItem("El charco");
                cbomunicipio.addItem("Olaya Herrera");
                cbomunicipio.addItem("Tumaco");
                break;
            case "Norte de Santander"://17 
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Cúcuta");
                break;

            case "Putumayo"://13
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Puerto Caicedo");
                cbomunicipio.addItem("Villa Garzón");
                break;
            case "Risaralda"://14
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Pereira");
                cbomunicipio.addItem("Santa Rosa de Cabal");
                cbomunicipio.addItem("Santuario");
                break;
            case "Tolima":// 20
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Ataco");
                break;
            case "Valle"://10
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Aguila");
                cbomunicipio.addItem("Buenaventura");
                cbomunicipio.addItem("Cali");
                cbomunicipio.addItem("Jamundí");
                cbomunicipio.addItem("La Florida");
                cbomunicipio.addItem("La Pradera");
                cbomunicipio.addItem("La Unión");
                cbomunicipio.addItem("Trujillo");
                cbomunicipio.addItem("Tuluá");
                cbomunicipio.addItem("Yumbo");

                break;
            case "Vichada"://15
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Puerto Carreño");
                break;
            case "Santander"://16
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("Bucaramanga");
                cbomunicipio.addItem("Vélez");
                break;
            default://otros
                cbomunicipio.removeAllItems();
                cbomunicipio.addItem("No seleccionado");
                break;
        }


    }//GEN-LAST:event_cbodeptoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnActualizarb;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnAgregarb;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnLimpiarb;
    public javax.swing.JButton btnbeneficiarios;
    public javax.swing.JButton btnbuscar;
    public javax.swing.JButton btnbuscarb;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btneliminarb;
    public javax.swing.JButton btnimprimir;
    public javax.swing.JButton btnimprimir1;
    public javax.swing.JComboBox<String> cbodepto;
    public javax.swing.JComboBox<String> cbomunicipio;
    public javax.swing.JComboBox<String> cbotipodocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public com.toedter.calendar.JDateChooser jdcfregistro;
    public com.toedter.calendar.JDateChooser jdcfresol;
    private javax.swing.JLabel lblcantbeneficiarios;
    public javax.swing.JRadioButton optdocumento;
    public javax.swing.JRadioButton optresolucion;
    public javax.swing.JTabbedPane pestResoluciones;
    public javax.swing.JTable tabla;
    public javax.swing.JTable tablab;
    public javax.swing.JTextField txtapellidobeneficiario;
    public javax.swing.JTextField txtapeprincipal;
    public javax.swing.JTextField txtbeneficiarias;
    public javax.swing.JTextField txtbuscar;
    public javax.swing.JTextField txtbuscarb;
    public javax.swing.JTextField txtcedulaprincipal;
    public javax.swing.JTextField txtemitidapor;
    public javax.swing.JTextField txtidbeneficiario;
    public javax.swing.JTextField txtidresolucion;
    public javax.swing.JTextField txtmonto;
    public javax.swing.JTextField txtnombrebeneficiario;
    public javax.swing.JTextField txtnomprincipal;
    public javax.swing.JTextField txtnumresolucion;
    public javax.swing.JTextField txtnumresolucionb;
    // End of variables declaration//GEN-END:variables

}
